# Generated by Django 5.0.4 on 2024-04-28 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ride", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_driver": True, "is_superuser": False},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rides_as_driver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
